version: 1
appendOnly: true
labels:
  - label: 'dependencies'
    type: 'pull_request'
    authors:
      - 'pre-commit-ci[bot]'
      - 'dependabot[bot]'
      - 'renovate[bot]'
  - label: 'bugfix'
    type: 'pull_request'
    title: '(?i).*fix.*'
  - label: 'feature'
    type: 'pull_request'
    title: '(?i).*feat.*'
  - label: 'breaking-change'
    type: 'pull_request'
    title: '(?i).*breaking[ -_]change.*'
  - label: 'github_actions'
    type: 'pull_request'
    title: '(?i).*(github[ -_]?actions?|workflow(s)?).*'
  - label: 'enhancement'
    type: 'pull_request'
    title: '(?i).*(enhance|improv(e|ement)).*'
  - label: 'documentation'
    type: 'pull_request'
    title: '(?i).*(docs|document|readme).*'
  - label: 'code-quality'
    type: 'pull_request'
    title: '(?i).*lint.*'
  - label: 'code-quality'
    type: 'pull_request'
    title: '(?i).*ruff.*'
  - label: 'code-quality'
    type: 'pull_request'
    title: '(?i).*mypy.*'
  - label: 'code-quality'
    type: 'pull_request'
    title: '(?i).*pytest.*'
  - label: 'code-quality'
    type: 'pull_request'
    title: '(?i).*coverage.*'
  - label: 'code-quality'
    type: 'pull_request'
    title: '(?i).*type-?check.*'
  - label: 'code-quality'
    type: 'pull_request'
    title: '(?i).*pre[ -_]?commit.*'
