name: prek Autoupdate

on:
  schedule:
    - cron: '0 5 * * *'
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  prek-autoupdate:
    uses: Snuffy2/prek-autoupdate/.github/workflows/prek_autoupdate.yml@v2
    permissions:
      contents: write
      pull-requests: write
    with:
      update-day: "3"
